In [1]:
import pandas as pd

In [2]:
dir1 = "C:/Users/82108/Desktop/cafe/"

In [3]:
df1 = pd.read_csv(dir1 + "강남 cafe_review.csv")

In [4]:
df1.head()

   Unnamed: 0         0                                                  1   2
0           0  카페노티드 청담  그냥 그렇다 생각했는데 다른 곳에서 도넛 먹고나면? ㄷ ㄷ 킹티드 .. 잘되는 이유...  4점
1           1  카페노티드 청담                우유크림 개맛있슴 근데 그만큼 혼잡해서 또 가고싶지 않은 곳..  3점
2           2  카페노티드 청담  도넛은 맛있는데 종업원들 대응이 너무 느려요. 한남이랑 삼성점도 가봤는데 여기가 유...  2점
3           3  카페노티드 청담  도넛이 맛은 있는데 줄이 진짜 너엉어ㅓㅓ어어어어무 길다 예약해서 가져갈거면 가고 가...  4점
4           4  카페노티드 청담                                              감사합니다  1점

In [5]:
df1 = df1.drop(['Unnamed: 0'], axis=1)

In [6]:
df1

             0                                                  1   2
0     카페노티드 청담  그냥 그렇다 생각했는데 다른 곳에서 도넛 먹고나면? ㄷ ㄷ 킹티드 .. 잘되는 이유...  4점
1     카페노티드 청담                우유크림 개맛있슴 근데 그만큼 혼잡해서 또 가고싶지 않은 곳..  3점
2     카페노티드 청담  도넛은 맛있는데 종업원들 대응이 너무 느려요. 한남이랑 삼성점도 가봤는데 여기가 유...  2점
3     카페노티드 청담  도넛이 맛은 있는데 줄이 진짜 너엉어ㅓㅓ어어어어무 길다 예약해서 가져갈거면 가고 가...  4점
4     카페노티드 청담                                              감사합니다  1점
...        ...                                                ...  ..
3037      어반81                                  친절하시고 와플도 맛있었어요☺️  5점
3038      어반81                                              보통이에요  3점
3039      어반81  골드치노는 안된대서 멜로모카랑 크림라떼 초코 마셨어요. 크림라떼는 취향이 아니어서 ...  4점
3040      어반81  골드치노6,5 연유베이스라 일반 카푸치노보단 달다. 분위기도 좋고 커피도 다양하고 ...  4점
3041     카페수수히                              오늘 갔다왔는데 사장님이 넘 친절하세요  5점

[3042 rows x 3 columns]

In [7]:
dir2 = "C:/Users/82108/Desktop/cafe/"
df2 = pd.read_csv(dir2 + "건대 cafe_review.csv")
df2 = df2.drop(['Unnamed: 0'], axis=1)
df2

          0                                                  1   2
0      아르무아                            가볼만해용 근데 치즈케이크 좀 물림,,,ㅎ  4점
1      아르무아                            단점은크게없는데 음료맛없어여 화장실은깨끗함  3점
2      아르무아                                              보통이에요  3점
3      아르무아                                              보통이에요  3점
4      아르무아  길가다가 분위기가 이뻐서 들어갔는데 직원분께서는 말 자체만 친절하지 말투와 어감은 ...  1점
...     ...                                                ...  ..
1390  하늘물고기                                                ㅇㅣ뻐   0
1391  하늘물고기                                        인도식 좌식 칵테일바   0
1392  하늘물고기  약간 특별함이 묻어나는 곳이다. 특별한 사람 특별한 날을 위해 이곳을 기억해 둔다면...   0
1393  하늘물고기  분위기도 좋고 위치도 좋고 와인마시기 좋음! 단, 신발을 벗고 아빠다리하구 앉아야하...   0
1394  하늘물고기   하물최고!!!!!!!!!! 칵테일너므맛있어요 생일날 기타치고 노래불러주시는것도 좋아용   5점

[1395 rows x 3 columns]

In [8]:
dir = "C:/Users/82108/Desktop/cafe/"
df3 = pd.read_csv(dir + "대학로 cafe_review.csv")
df3 = df3.drop(['Unnamed: 0'], axis=1)
df3

           0                                                  1   2
0       학림다방                                           꾸준히 가게 됨  3점
1       학림다방                                                좋아요  4점
2       학림다방                                               최고예요  5점
3       학림다방                                                좋아요  4점
4       학림다방                                              2층이 갑  4점
...      ...                                                ...  ..
1872  곰다방 본점                 와플 not bad 견과류를 듬뿍 넣어주는 아포가토가 맛잇었다   0
1873  곰다방 본점                                       곰 고문 현장...;;   0
1874  곰다방 본점                     와플 허니브레드 아메리카노 아이스크림이곰모양인 빙수쵝오   0
1875  곰다방 본점  대학로에 위치한 곰다방~~ 커피며 음료며 특히 빙수최고ㅋ 고파여서 모이면 아가들 무...   0
1876  곰다방 본점           아기자기함이 물씬풍기는 카페  환상적인 곰라떼아트와 커피맛 또한 좋은카페   0

[1877 rows x 3 columns]

In [9]:
dir = "C:/Users/82108/Desktop/cafe/"
df4 = pd.read_csv(dir + "홍대 cafe_review.csv")
df4 = df4.drop(['Unnamed: 0'], axis=1)
df4

           0                                                  1   2
0      앤디스커피                                               별로예요  1점
1      앤디스커피                                   루프탑이 있어서 좋아용 ㅎㅎㅎ  4점
2      앤디스커피  음료 괜춘헌디.. 갠적으로 맛있었음 근데 루프탑 청국장 냄새 오지는 거 인정,, 그...  4점
3      앤디스커피                                                맛없음  2점
4      앤디스커피  5점준 사람들 평가내역보면 왜 앤더스커피밖에 평가가 없냐? ㅋㅋㅋ  리뷰쓰고 '상식...  2점
...      ...                                                ...  ..
4055  그린클라우드                                           오늘의 저녁약속   0
4056  그린클라우드                                           레몬차가 맛잇는   0
4057  그린클라우드                                      한적, 조용, 커피, 차   0
4058  그린클라우드     분위기 진짜 좋움! 오렌지 클라우드 맛있어요~ 홍대에 유일하게 조용한카페~~~~^^  5점
4059  그린클라우드  스터디카페로 좋네여. 다들 스터디 목적으로 오시기도 하고. 좌석도 많아서 혼자 오시...  4점

[4060 rows x 3 columns]

In [10]:
dir = "C:/Users/82108/Desktop/cafe/"
df5 = pd.read_csv(dir + "이태원 cafe_review.csv")
df5 = df5.drop(['Unnamed: 0'], axis=1)
df5

                  0                                                  1   2
0         챔프커피 2작업실  이태원 커피 신맛 없는 원두로 주문했는데 신세계였어요 구수하면서 달달한 맛. 약간 ...  5점
1         챔프커피 2작업실  커피 맛이 좋대서 너무 기대하고 간듯요 시그니쳐 커피는 왜 시그니쳐인지 잘 모르겠어...  3점
2         챔프커피 2작업실                                     쿠키 맛집 커피도 맛있어요  5점
3         챔프커피 2작업실                                                좋아요  4점
4         챔프커피 2작업실                                   응대는 보통. 커피도 보통.   3점
...             ...                                                ...  ..
1293        실수투성이 밤        사장님이 불친절해서 별로였어요~ 골목 골목을 지나야 해서 가게 찾기도 어려워요  2점
1294        실수투성이 밤           감성돋는 실수 커피 맛있어요! 괜찮아, 어차피 실수로 만들어진 우리니까.  3점
1295  마리웨일237 경리단길점                                               최고예요  5점
1296  마리웨일237 경리단길점                                                좋아요  4점
1297  마리웨일237 경리단길점                                                좋아요  4점

[1298 rows x 3 columns]

In [11]:
dir = "C:/Users/82108/Desktop/cafe/"
df6 = pd.read_csv(dir + "가로수길 cafe_review.csv")
df6 = df6.drop(['Unnamed: 0'], axis=1)
df6

               0                                                  1   2
0     C27 가로수길본점  치즈케이크 종류가 정말 다양하고 맛있다. 카페 분위기도 괜찮다.  근데 한 조각이 ...  2점
1     C27 가로수길본점                                              케익 존맛  5점
2     C27 가로수길본점                                         케이크가 맛있긴 함  3점
3     C27 가로수길본점  네고왕덕분에 할인받았지만 할인된가격도 비싸다 비싼값하면 괜찮은데 차라리 파바 치즈케...  1점
4     C27 가로수길본점                                                맛있셔  5점
...          ...                                                ...  ..
1450         피르마                                               최고예요  5점
1451         피르마                                            Dessert  3점
1452        야카모즈                         신사에서 이렇게 조용하고 친절한 곳이 또 있을까  5점
1453        야카모즈                                 커피맛 굿. 외진 곳이라 조용함.  4점
1454        야카모즈                                              보통이에요  3점

[1455 rows x 3 columns]

In [12]:
dir = "C:/Users/82108/Desktop/cafe/"
df7 = pd.read_csv(dir + "이태원 cafe_review.csv")
df7 = df7.drop(['Unnamed: 0'], axis=1)
df7

                  0                                                  1   2
0         챔프커피 2작업실  이태원 커피 신맛 없는 원두로 주문했는데 신세계였어요 구수하면서 달달한 맛. 약간 ...  5점
1         챔프커피 2작업실  커피 맛이 좋대서 너무 기대하고 간듯요 시그니쳐 커피는 왜 시그니쳐인지 잘 모르겠어...  3점
2         챔프커피 2작업실                                     쿠키 맛집 커피도 맛있어요  5점
3         챔프커피 2작업실                                                좋아요  4점
4         챔프커피 2작업실                                   응대는 보통. 커피도 보통.   3점
...             ...                                                ...  ..
1293        실수투성이 밤        사장님이 불친절해서 별로였어요~ 골목 골목을 지나야 해서 가게 찾기도 어려워요  2점
1294        실수투성이 밤           감성돋는 실수 커피 맛있어요! 괜찮아, 어차피 실수로 만들어진 우리니까.  3점
1295  마리웨일237 경리단길점                                               최고예요  5점
1296  마리웨일237 경리단길점                                                좋아요  4점
1297  마리웨일237 경리단길점                                                좋아요  4점

[1298 rows x 3 columns]

In [22]:
traindata = pd.concat([df1, df2, df3, df4, df5, df6, df7])
traindata.tail(60)

                  0                                                  1   2
1238          스탠딩커피                                           블루 레모네이드   0
1239          스탠딩커피  용산에서 군복무했던 친구가 자주가던 카페. 경리단길의 대표 카페라나 뭐라나. 블루레...   0
1240          스탠딩커피                                              스탠딩커피   0
1241          스탠딩커피                                       날 더울때 레모네이드♥   0
1242          스탠딩커피                  내가 좋아하는 커피숍. 1.스탠딩커피 2.전광수커피 3.스벅   0
1243          스탠딩커피                                              레몬에이드   0
1244          스탠딩커피                    너~~~~~무 셔서 속쓰리다ㅠㅠ근데먹고싶어지는 레모네이드   0
1245          스탠딩커피                                         블루레모네이드 짱!   0
1246          스탠딩커피                                           레몬에이드 시다   0
1247          스탠딩커피                                       돈 많이 벌겠구나...   0
1248          스탠딩커피                                        파란색 레모네이드!!   0
1249          스탠딩커피                                  블루레몬에이드가 정말 최고!!!   0
1250          스탠딩커피                                [이태원 맛집]  5천원 레몬에이드   0
1251          스탠딩커피           스탠딩커피 레모네이드는 진리!!!비타민씨가 부족하다면 바로 여기!!!^^   0
1252          스탠딩커피                                             ✨👍오랜만에   0
1253          스탠딩커피  우리집에서 이 곳까지 7km.. 이 밤에 달려가기란 좀 무리군요. 레몬에이드는 만들...   0
1254          스탠딩커피  레몬에이드 완전 좋아~   그런데 얼음이 많이 녹으니 점점 밍밍 해지지만 끝까지 쪽~쪽~   0
1255          스탠딩커피                              트랜디한 감성이 녹아있는 메뉴와 분위기   0
1256          스탠딩커피                                여름엔 시원한 레몬에이드 테이크아웃   0
1257          스탠딩커피                 레머레이드라길레 별 생각 없이 먹었지만..맛있었다... OTL   0
1258          스탠딩커피                                     워낙유명한'블루레몬에이드'   0
1259          스탠딩커피            직접 레몬을 짜서 만드는 스탠딩커피, 쌔그러운 블루레몬에이드 좋아 :)   0
1260          스탠딩커피           여긴 블루레몬에이드가 유명함 그렇지만 사진은 아이스라떼 밖에 없는 관계로   0
1261          스탠딩커피                                             레몬에이드♡   0
1262          스탠딩커피                                        사랑해레몬에이드 ㅋㅋ   0
1263          스탠딩커피                                      레몬에이드가 최고여 ㅎㅎ   0
1264          스탠딩커피                                  샤콤한 레몬에이드'ㅠ' 침이쥴쥴   0
1265          스탠딩커피                                         레몬에이드가 최고!   0
1266          스탠딩커피                                                맛있음   0
1267          스탠딩커피                     블루 레몬에이드 요즘같이 열대야일때 자꾸자꾸 생각나요ㅠ   0
1268          스탠딩커피                 레몬씨까지 씹히는 진정한 레몬에이드!^^ 진짜 레몬에이드!ㅋㅋ   0
1269          스탠딩커피                                           블루레몬에이드~   0
1270          스탠딩커피                                      블루레몬에이드 구으뜨~!   0
1271          스탠딩커피                                            싸고 맛있고.   0
1272          스탠딩커피                                           커피,레몬에이드   0
1273          스탠딩커피                                   블루 레몬에이드의 원조랍니다©   0
1274          스탠딩커피  내가 먹어본 최고의 레몬에이드~ 특유의 녹색이 트레이드마크! 하지만 엄청 시다는것만...   0
1275          스탠딩커피  매력있어요. 커피도 다른 음료들도 참 개성있게 맛있는 곳이예요. 분위기도 이국적이라...  4점
1276            카페인                                         개인작업하기 좋아요  5점
1277            카페인                                          평범 장소가 넓음  3점
1278            카페인                                                좋아요  4점
1279            카페인                                              보통이에요  3점
1280         훔볼트아지트                                               최고예요  5점
1281         훔볼트아지트  알바인지 직원인지 모르겠으나 카운터 보시는 여성분 정말 불친절합니다. 계속 똥 씹은...  1점
1282         훔볼트아지트  간판 H 마음에 들어서 들어왔는데 빵도 맛있고 커피도 맛있고 내부도 이쁘고 분위기도...  5점
1283         훔볼트아지트                                        예쁜공간. 맛있는 빵  5점
1284         훔볼트아지트                                          빵이 다 맛있음.  4점
1285         훔볼트아지트                         너무 꾸덕하지 않고 포슬하지만 진하 치즈케이크   4점
1286          케르반카페  케르반 베이커리의 바클라바를 낱개로 차와 함께 즐길 수 있다. 과자를 따뜻하게 데워...  3점
1287          케르반카페  외국에 온 느낌 직원친절 홍차시키니 쿠키도 주심 평일 낮에 왔더니 한산해서 잘 쉬다 나옴  4점
1288          케르반카페                                             그저그러네요  3점
1289          카페미주리                        분위기 좋고 커피 맛있어요 바질 스콘 맛나요~!!  4점
1290            벨리븐                                               최고예요  5점
1291            벨리븐                                               최고예요  5점
1292            벨리븐           잔잔하고 여유로워서 너무 편하고 좋았어요 티 마시면서 릴렉스 제데로 함~  5점
1293        실수투성이 밤        사장님이 불친절해서 별로였어요~ 골목 골목을 지나야 해서 가게 찾기도 어려워요  2점
1294        실수투성이 밤           감성돋는 실수 커피 맛있어요! 괜찮아, 어차피 실수로 만들어진 우리니까.  3점
1295  마리웨일237 경리단길점                                               최고예요  5점
1296  마리웨일237 경리단길점                                                좋아요  4점
1297  마리웨일237 경리단길점                                                좋아요  4점

In [14]:
traindata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14425 entries, 0 to 1297
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       14425 non-null  object
 1   1       14321 non-null  object
 2   2       14425 non-null  object
dtypes: object(3)
memory usage: 450.8+ KB

In [15]:
traindata.to_csv("traindata.csv")

In [25]:
dir = "C:/Users/82108/Desktop/cafe/"
df5 = pd.read_csv(dir + "강남 cafe_namelist.csv")
df5 = df5.drop(['Unnamed: 0', '0'], axis=1)
df5

             cafe_name
0        강남카페 카페노티드 청담
1         강남카페 블루보틀 역삼
2        강남카페 랑데자뷰 강남점
3      강남카페 꽁티드툴레아 도산점
4    강남카페 카페캠프통 압구정살롱점
5       강남카페 10꼬르소꼬모카페
6         강남카페 썸띵어바웃커피
7            강남카페 카페써드
8      강남카페 펠트커피 도산공원점
9   강남카페 아우어베이커리 싸이더스점
10        강남카페 소진담 신사점
11           강남카페 껠끄쇼즈
12           강남카페 파넬카페
13             강남카페 고센
14           강남카페 달링키친
15            강남카페 에잇디
16          강남카페 로얄마카롱
17     강남카페 크리에잇쿠키 역삼점
18             강남카페 미엘
19           강남카페 겟썸커피
20            강남카페 세드라
21  강남카페 더닐크팩토리 가로수길지점
22            강남카페 맷카페
23         강남카페 SM타운카페
24          강남카페 이브닝블루
25     강남카페 세시셀라 도산공원점
26         강남카페 마일스톤커피
27          강남카페 클라우즈비
28      강남카페 카페레이어스튜디오
29     강남카페 빵어니스타 압구정점

In [26]:
dir = "C:/Users/82108/Desktop/cafe/"
df6 = pd.read_csv(dir + "건대 cafe_namelist.csv")
df6 = df6.drop(['Unnamed: 0', '0'], axis=1)
df6

               cafe_name
0              건대카페 아르무아
1               건대카페 도우터
2              건대카페 카페히릿
3            건대카페 아오스요거트
4              건대카페 최가커피
5           건대카페 비에이치테이블
6                건대카페 밀피
7          건대카페 랑데자뷰 건대점
8       건대카페 커피나무 건대입구역점
9              건대카페 냥토피아
10            건대카페 마우스레빗
11            건대카페 북카페세모
12           건대카페 카페K375
13           건대카페 CAFE22
14       건대카페 카페온더플랜 건대점
15       건대카페 스타벅스 건대입구점
16          건대카페 오페뜨 건대점
17             건대카페 온더볼륨
18            건대카페 플레이독스
19           건대카페 앨리스룸카페
20  건대카페 키랩보드게임 룸카페 건대본점
21         건대카페 도쿄빙수 건대점
22       건대카페 리밀커피&밀리마카롱
23     건대카페 투썸플레이스 건대입구점
24         건대카페 스타벅스 건국대
25            건대카페 레이니레인
26            건대카페 카페오로시
27         건대카페 홍콩다방 건대점
28       건대카페 칼레오 커피로스터스
29        건대카페 다빈치보드게임카페
30        건대카페 타이거슈가 건대점
31             건대카페 커피마켓
32         건대카페 카페호이 자양점
33          건대카페 벨롱에스프레소
34               건대카페 소단
35  건대카페 히어로보드게임카페 건대1호점
36    건대카페 할리스커피 건대일감호수점
37       건대카페 설빙 건대직영2호점
38             건대카페 카페코튼
39            건대카페 치즈팩토리
40     건대카페 넥스트에디션 건대2호점

In [27]:
dir = "C:/Users/82108/Desktop/cafe/"
df7 = pd.read_csv(dir + "대학로 cafe_namelist.csv")
df7 = df7.drop(['Unnamed: 0', '0'], axis=1)
df7

                cafe_name
0              대학로카페 학림다방
1             대학로카페 카페키이로
2                대학로카페 칠린
3           대학로카페 메종드아베크엘
4         대학로카페 빌리엔젤 대학로점
5         대학로카페 커피한약방 혜화점
6                대학로카페 개뿔
7               대학로카페 블루룸
8       대학로카페 폴인팬케이크 대학로점
9          대학로카페 스노브 대학로점
10          대학로카페 벌툰 대학로점
11             대학로카페 공공거실
12            대학로카페 카페혜화동
13             대학로카페 하이제씨
14             대학로카페 슬로스텝
15               대학로카페 타셴
16     대학로카페 혜화역4번출구카페제이드
17             대학로카페 마띠에르
18             대학로카페 해로커피
19         대학로카페 쁘띠렌 대학로점
20             대학로카페 서화커피
21        대학로카페 스타벅스 혜화역점
22             대학로카페 까페몽스
23  대학로카페 덤앤더머 방탈출카페 대학로점
24            대학로카페 카페트레블
25             대학로카페 타스카페
26            대학로카페 낫컴플리트
27     대학로카페 스타벅스 마로니에공원점
28        대학로카페 미어캣파크 혜화점
29             대학로카페 일월일일
30        대학로카페 오후홍콩 대학로점
31           대학로카페 브라운에비뉴
32             대학로카페 헤이커피
33            대학로카페 에그마카슈
34             대학로카페 학림커피
35          대학로카페 제뉴어리피크닉
36       대학로카페 미스터힐링 대학로점
37       대학로카페 비트포비아 대학로점
38          대학로카페 공차 대학로점
39            대학로카페 시크릿챔버
40       대학로카페 로벨리아듀카페&와인
41        대학로카페 설빙 혜화대학로점

In [28]:
dir = "C:/Users/82108/Desktop/cafe/"
df8 = pd.read_csv(dir + "홍대 cafe_namelist.csv")
df8 = df8.drop(['Unnamed: 0', '0'], axis=1)
df8

               cafe_name
0                홍대카페 공휴
1       홍대카페 소마드로잉카페 홍대점
2           홍대카페 피오니 홍대점
3         홍대카페 르쁘띠푸 홍대본점
4          홍대카페 랑데자뷰 상수점
5          홍대카페 943킹스크로스
6          홍대카페 룸즈에이 홍대점
7         홍대카페 테일러커피 서교점
8              홍대카페 톤앤매너
9            홍대카페 바나나하루키
10         홍대카페 비라티오 홍대점
11    홍대카페 도화서가 홍대점(휴업중)
12            홍대카페 앤디스커피
13            홍대카페 시루케이크
14            홍대카페 어반플랜트
15          홍대카페 오츠에스프레소
16             홍대카페 버터밀크
17             홍대카페 쇼콜라윰
18  홍대카페 히어로보드게임카페 홍대1호점

In [30]:
traindata_namelist = pd.concat([df5, df6, df7, df8])
traindata_namelist

               cafe_name
0          강남카페 카페노티드 청담
1           강남카페 블루보틀 역삼
2          강남카페 랑데자뷰 강남점
3        강남카페 꽁티드툴레아 도산점
4      강남카페 카페캠프통 압구정살롱점
..                   ...
14            홍대카페 어반플랜트
15          홍대카페 오츠에스프레소
16             홍대카페 버터밀크
17             홍대카페 쇼콜라윰
18  홍대카페 히어로보드게임카페 홍대1호점

[132 rows x 1 columns]

In [32]:
traindata_namelist.to_csv("traindata_namelist.csv")